# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametrizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=70)),
                ('edad', models.CharField(blank=True, max_length=2)),
                ('correo', models.CharField(blank=True, max_length=50)),
                ('experiencia_anos', models.CharField(blank=True, max_length=2)),
                ('experiencia_horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Profesiones')),
            ],
            options={
                'verbose_name_plural': 'Crear Usuarios',
            },
        ),
    ]
