# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20170520_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='certificado',
            field=models.TextField(blank=True),
        ),
    ]
