# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuarios_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='base64',
            field=models.TextField(blank=True),
        ),
    ]
