# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuarios_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='base64',
        ),
    ]
