# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import parametrizacion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(blank=True, max_length=50)),
                ('foto', models.ImageField(blank=True, upload_to=parametrizacion.models.profesiones_directory_path)),
            ],
            options={
                'verbose_name_plural': 'Crear Profesiones',
            },
        ),
    ]
