# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import parametrizacion.models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesiones',
            name='foto',
            field=models.ImageField(upload_to=parametrizacion.models.profesiones_directory_path),
        ),
        migrations.AlterField(
            model_name='profesiones',
            name='profesion',
            field=models.CharField(max_length=50),
        ),
    ]
